[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci || npm install"]

[phases.build]
cmds = ["node ./node_modules/prisma/build/index.js generate"]

[start]
cmd = "npm start"
